#########################################################################
# Title:         Cloudbox: System | sysctl Tasks                        #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: sysctl | Tuning
  ignore_errors: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    # Enable tcp_window_scaling
    - { name: net.ipv4.tcp_window_scaling, value: 1 }
    # Increase rmem_max test buffer limit to 128 MB (need double for app buffer)
    - { name: net.core.rmem_max, value: 134217728 }
    # Increase wmem_max test buffer limit to 64 MB
    - { name: net.core.wmem_max, value: 67108864 }
    # Increase tcp_rmem autotune buffer limit to 32 MB
    - { name: net.ipv4.tcp_rmem, value: "4096 131072 134217728" }
    # Increase tcp_wmem autotune buffer limit to 32 MB
    - { name: net.ipv4.tcp_wmem, value: "4096 65536 67108864" }
    # Set tcp_congestion_control to bbr. lowat tune is needed for bbr to do its
    # thing.
    - { name: net.ipv4.tcp_congestion_control, value: bbr }
    - { name: net.ipv4.tcp_notsent_lowat, value: 16384 }
    # Increase system file descriptor limit
    - { name: fs.file-max, value: 100000 }
    # Reduce swappiness
    - { name: vm.swappiness, value: 10 }
    # Set dirty_ratio
    - { name: vm.dirty_ratio, value: 10 }
    # Set dirty_background_ratio
    - { name: vm.dirty_background_ratio, value: 3 }
    # Increase min reserved kernel memory - 64k was causing kernel to run out of
    # buffers.
    - { name: vm.min_free_kbytes, value: 262144 }
    # Set somaxconn to 1024
    - { name: net.core.somaxconn, value: 1024 }
    # Increase netdev_max_backlog
    - { name: net.core.netdev_max_backlog, value: 10000 }
    # Increase tcp_max_syn_backlog
    - { name: net.ipv4.tcp_max_syn_backlog, value: 30000 }
    # Increase tcp_max_tw_buckets
    - { name: net.ipv4.tcp_max_tw_buckets, value: 2000000 }
    # Enable tcp_tw_reuse
    - { name: net.ipv4.tcp_tw_reuse, value: 1 }
    # Enable tcp_mtu_probing
    - { name: net.ipv4.tcp_mtu_probing, value: 1 }
    # Enable tcp_sack
    - { name: net.ipv4.tcp_sack, value: 1 }
    # Don't increase tcp_adv_win_scale - later kernels should have this 1 due to
    # skb truesize fixes.
    - { name: net.ipv4.tcp_adv_win_scale, value: 1 }
    # Enable tcp_rfc1337
    - { name: net.ipv4.tcp_rfc1337, value: 1 }
    # Increase tcp_fin_timeout
    - { name: net.ipv4.tcp_fin_timeout, value: 10 }
    # Disable tcp_slow_start_after_idle
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
    # Increase udp_rmem_min
    - { name: net.ipv4.udp_rmem_min, value: 8192 }
    # Increase udp_wmem_min
    - { name: net.ipv4.udp_wmem_min, value: 8192 }
    # Disable accept_source_route
    - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
    # Disable accept_redirects
    - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
    # Disable secure_redirects
    - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
    # Set default_qdisc to fq
    - { name: net.core.default_qdisc, value: fq }
    # Set max_user_watches for plex inotify
    - { name: fs.inotify.max_user_watches, value: 524288 }
    # Set net.core.netdev_budget
    - { name: net.core.netdev_budget, value: 1000 }

- name: sysctl | Check to see if '/proc/sys/net/core/netdev_budget_usecs' exists
  stat:
    path: "/proc/sys/net/core/netdev_budget_usecs"
  register: netdev_budget_usecs

- name: "sysctl | Tuning - 'netdev_budget_usecs'"
  ignore_errors: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    # Set netdev_budget_usecs
    - { name: net.core.netdev_budget_usecs, value: 5000 }
  when: netdev_budget_usecs.stat.exists
